### ISSUE TITLE
Issue: container4

### ISSUE THREAD

**Issue by ifchang** [behappywendy/transparent_text_effect#18]
### Desc
新增透明字+背景效果

---

### Tasks
- [ ] layout
- [ ] feature
- [ ] testing

**Comment by southAndy** [comment]
改一下標題！
要開始做了嗎？

**Comment by ifchang** [comment]
對, 要開始做了, 標題有格式嗎？

**Comment by southAndy** [comment]
就想說大家看起來統一ＸＤ
Issue:contianer4

**Comment by ifchang** [comment]
收到！
